name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/python-3.12-slim-local-pt-br:latest .

      - name: Push da imagem
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/python-3.12-slim-local-pt-br:latest
